const actionTypes = Object.freeze({
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",

  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",

  FETCH_ALL_SERVICES_START: "FETCH_ALL_SERVICES_START",
  FETCH_ALL_SERVICES_SUCCESS: "FETCH_ALL_SERVICES_SUCCESS",
  FETCH_ALL_SERVICES_FAILED: "FETCH_ALL_SERVICES_FAILED",

  FETCH_ALL_FIELDS_START: "FETCH_ALL_FIELDS_START",
  FETCH_ALL_FIELDS_SUCCESS: "FETCH_ALL_FIELDS_SUCCESS",
  FETCH_ALL_FIELDS_FAILED: "FETCH_ALL_FIELDS_FAILED",
});

export default actionTypes;
